-- Full purchase invoice metadata (Excel + manual)
ALTER TABLE purchase_invoices
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN IF NOT EXISTS invoice_type TEXT,
  ADD COLUMN IF NOT EXISTS printed_subtotal NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS printed_discount NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS printed_taxable NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS printed_cgst NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS printed_sgst NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS printed_grand_total NUMERIC(12,2);

ALTER TABLE purchase_lines
  ADD COLUMN IF NOT EXISTS hsn TEXT,
  ADD COLUMN IF NOT EXISTS brand TEXT,
  ADD COLUMN IF NOT EXISTS uom TEXT DEFAULT 'PCS',
  ADD COLUMN IF NOT EXISTS mrp NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS disc_percent NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS taxable NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS cgst_percent NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS sgst_percent NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC(12,2);
